name: Build, Publish and Scan (Managed)
on:
  workflow_dispatch:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]
  release:
    types: [published]
jobs:
  build-publish-scan:
    uses: BERDataLakehouse/.github/.github/workflows/build_publish_scan.yaml@main
    permissions:
      contents: read
      packages: write
